# Generated by Django 5.2 on 2025-05-07 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الشركة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='شعار الشركة')),
            ],
            options={
                'verbose_name': 'شركة مصنعة',
                'verbose_name_plural': 'الشركات المصنعة',
            },
        ),
        migrations.CreateModel(
            name='ErrorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obd_code', models.CharField(max_length=10, unique=True, verbose_name='كود العطل')),
                ('description', models.TextField(verbose_name='وصف العطل')),
                ('severity', models.CharField(choices=[('LOW', 'منخفضة'), ('MEDIUM', 'متوسطة'), ('HIGH', 'عالية'), ('CRITICAL', 'حرجة')], max_length=10, verbose_name='خطورة العطل')),
                ('emergency_action', models.CharField(blank=True, max_length=255, null=True, verbose_name='إجراء الطوارئ')),
                ('repair_difficulty', models.CharField(choices=[('EASY', 'سهل'), ('MEDIUM', 'متوسط'), ('HARD', 'صعب')], max_length=10, verbose_name='صعوبة الإصلاح')),
            ],
            options={
                'verbose_name': 'كود عطل',
                'verbose_name_plural': 'أكواد الأعطال',
            },
        ),
        migrations.CreateModel(
            name='ErrorCodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_prefix', models.CharField(max_length=10, unique=True, verbose_name='بادئة الكود')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('category_type', models.CharField(choices=[('ENGINE', 'المحرك'), ('TRANSMISSION', 'ناقل الحركة'), ('FUEL', 'نظام الوقود'), ('IGNITION', 'نظام الإشعال'), ('EMISSION', 'نظام العادم'), ('ELECTRICAL', 'النظام الكهربائي'), ('ABS', 'نظام المكابح'), ('HVAC', 'نظام التكييف'), ('OTHER', 'أخرى')], max_length=20, verbose_name='نوع الفئة')),
                ('description', models.TextField(verbose_name='وصف الفئة')),
            ],
            options={
                'verbose_name': 'فئة أكواد الأعطال',
                'verbose_name_plural': 'فئات أكواد الأعطال',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('year', models.IntegerField(verbose_name='سنة الصنع')),
                ('engine_type', models.CharField(max_length=100, verbose_name='نوع المحرك')),
                ('common_issues', models.TextField(blank=True, null=True, verbose_name='الأعطال الشائعة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='صورة السيارة')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='car_diagnostics.carbrand', verbose_name='الشركة المصنعة')),
            ],
            options={
                'verbose_name': 'سيارة',
                'verbose_name_plural': 'السيارات',
                'unique_together': {('brand', 'model', 'year', 'engine_type')},
            },
        ),
        migrations.CreateModel(
            name='CarError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_causes', models.TextField(verbose_name='الأسباب الشائعة')),
                ('solutions', models.TextField(blank=True, null=True, verbose_name='الحلول المقترحة')),
                ('repair_steps', models.TextField(blank=True, null=True, verbose_name='خطوات الإصلاح')),
                ('estimated_cost', models.CharField(blank=True, max_length=100, null=True, verbose_name='التكلفة التقديرية')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_errors', to='car_diagnostics.car', verbose_name='السيارة')),
                ('error_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_errors', to='car_diagnostics.errorcode', verbose_name='كود العطل')),
            ],
            options={
                'verbose_name': 'عطل السيارة',
                'verbose_name_plural': 'أعطال السيارات',
                'unique_together': {('car', 'error_code')},
            },
        ),
        migrations.AddField(
            model_name='errorcode',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_codes', to='car_diagnostics.errorcodecategory', verbose_name='فئة الكود'),
        ),
        migrations.CreateModel(
            name='RepairResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('resource_type', models.CharField(choices=[('VIDEO', 'فيديو'), ('ARTICLE', 'مقالة'), ('MANUAL', 'دليل'), ('TOOL', 'أداة')], max_length=20, verbose_name='نوع المورد')),
                ('url', models.URLField(verbose_name='الرابط')),
                ('car_error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='car_diagnostics.carerror', verbose_name='عطل السيارة')),
            ],
            options={
                'verbose_name': 'مورد إصلاح',
                'verbose_name_plural': 'موارد الإصلاح',
            },
        ),
    ]
